### ISSUE TITLE
Tweeki throwing " Uncaught Error: Call to undefined function wfRunHooks()"

### ISSUE THREAD

**Issue by jcklpe** [thaider/Tweeki#122]
Hi, 

I'm a designer learning to code. I wanted to make my own wiki skin and Tweeki seemed like the most easy to follow and structured skin that I could find. 

But when I clone the repo into my skins folder and load it in my LocalSettings.php and then either turn it on through the preferences or set it as the default skin I get the following error:

```
 Fatal error: Uncaught Error: Call to undefined function wfRunHooks() in /var/www/mediawiki/skins/Tweeki/includes/SkinTweeki.php:63 Stack trace: #0 /var/www/mediawiki/includes/skins/SkinTemplate.php(224): SkinTweeki->initPage(Object(OutputPage)) #1 /var/www/mediawiki/includes/OutputPage.php(2597): SkinTemplate->outputPage() #2 /var/www/mediawiki/includes/exception/MWExceptionRenderer.php(136): OutputPage->output() #3 /var/www/mediawiki/includes/exception/MWExceptionRenderer.php(53): MWExceptionRenderer::reportHTML(Object(Error)) #4 /var/www/mediawiki/includes/exception/MWExceptionHandler.php(98): MWExceptionRenderer::output(Object(Error), 2) #5 /var/www/mediawiki/includes/exception/MWExceptionHandler.php(172): MWExceptionHandler::report(Object(Error)) #6 /var/www/mediawiki/includes/exception/MWExceptionHandler.php(144): MWExceptionHandler::handleException(Object(Error)) #7 [internal function]: MWExceptionHandler::handleUncaughtException(Object(Error)) #8 {main} thrown in /var/www/mediawiki/skins/Tweeki/includes/SkinTweeki.php on line 63
```

My installation of mediawiki seems pretty standard. I have only added a couple of extensions such as CodeMirror, BetaFeatures, VisualEditor and the 2017 WikitextEditor. 

Here's my LocalSettings file:

```
<?php
# This file was automatically generated by the MediaWiki 1.32.0-alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if (!defined('MEDIAWIKI')) {
    exit;
}

$wgSitename = "Λόγος";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wiki.jackalope.tech";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "redacted";
$wgPasswordSender = "redacted";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "redacted";
$wgDBuser = "redacted";
$wgDBpassword = "redacted";

# MySQL specific settings
$wgDBprefix = "wiki_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "redacted";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "redacted";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-nc-sa/4.0/";
$wgRightsText = "Creative Commons Attribution-NonCommercial-ShareAlike";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-nc-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

# End of automatically generated settings.
# Add more configuration options below.

//- SKINS
## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";
// load vector skin
wfLoadSkin('Vector');
wfLoadSkin('foreground');
wfLoadSkin('Tweeki');

//- EXTENSIONS
//-Visual editor
wfLoadExtension('VisualEditor');

// Enable by default for everybody
$wgDefaultUserOptions['visualeditor-enable'] = 1;

// Optional: Set VisualEditor as the default for anonymous users
// otherwise they will have to switch to VE
// $wgDefaultUserOptions['visualeditor-editor'] = "visualeditor";

// Don't allow users to disable it
$wgHiddenPrefs[] = 'visualeditor-enable';

// OPTIONAL: Enable VisualEditor's experimental code features
#$wgDefaultUserOptions['visualeditor-enable-experimental'] = 1;

$wgVirtualRestConfig['modules']['parsoid'] = array(
    // URL to the Parsoid instance
    // Use port 8142 if you use the Debian package
    'url' => 'http://localhost:8000',
    // Parsoid "domain", see below (optional)
    'domain' => 'wiki.jackalope.tech',
    // Parsoid "prefix", see below (optional)
    'prefix' => 'wiki.jackalope.tech',
);

//- Beta Features
wfLoadExtension('BetaFeatures');

//- 2017 Wiki Text
$wgVisualEditorEnableWikitext = true;
$wgDefaultUserOptions['visualeditor-newwikitext'] = 1;
$wgHiddenPrefs[] = 'visualeditor-newwikitext';

//- Code Mirror
wfLoadExtension('CodeMirror');
$wgDefaultUserOptions['usecodemirror'] = 1;

//- Echo Notifications
wfLoadExtension('Echo');

//- CLDR (localizes based on location)
wfLoadExtension('cldr');

//- Parser Functions
wfLoadExtension('ParserFunctions');
$wgPFEnableStringFunctions = true;

//- Structured Discussions
wfLoadExtension('Flow');
$wgNamespaceContentModels[NS_TALK] = 'flow-board';
$wgNamespaceContentModels[NS_USER_TALK] = 'flow-board';
$wgNamespaceContentModels[NS_PROJECT_TALK] = 'flow-board';
$wgNamespaceContentModels[NS_CATEGORY_TALK] = 'flow-board';
$wgNamespaceContentModels[NS_USER] = 'flow-board';
$wgGroupPermissions['user']['flow-create-board'] = true;
// $wgContentHandlerUseDB = false;

//- CUSTOMIZATIONS
//- Thumbnail Size
$wgThumbLimits = array(
    150,
    250,
    500,
);
$wgDefaultUserOptions['thumbsize'] = 3;

/////////////////////////
//-DISPLAY VERBOSE ERROR CODES
error_reporting(-1);
ini_set('display_errors', 1);
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;


```

@thaider 

Any ideas on what might be causing this?

Also would you say that this is a good skin to use as a starter for my own skin? I honestly can't make heads or tails of the structure of the default Vector skin, as I have a limited php background and it seems to rely heavily on that rather than the classic html5/css3/VanillaJavascript that I'm more used to.

**Comment by jcklpe** [comment]
I've found the problem. wfRunHooks was removed in 1.32

Should the skin be fixed to account for this or should wfRunHooks be added into Tweeki? I don't know a whole bunch about how this stuff works.

**Comment by jcklpe** [comment]
@thaider  I mostly want to create my own skin because I want the practice, purely as a personal learning experience. Main thing I want to do is add in webpack support. The big thing I'm trying to get from Tweeki is a grokkable file structure because Vector is extremely confusing for me. 

 I understand how a CSS, Less, and SCSS work etc, but I don't get what all the extra PHP stuff is. I'm even experienced with how a theme is structured etc in a PHP based CMS like Wordpress, or how a build system like webpack or a React/Angular app works, but the structure of something like Vector seems very confusing to me. I don't know if it's confusing because Vector was originally made in 2009, or if it's because Mediawiki as a platform has archaic ways of doing things, or if I'm just not a very good developer (I'm still very new to development afterall) Tweeki seems moderately better as it's at least based on bootstrap which I am very familiar with. 

Would you happen to be able to explain why/how a MW skin is structured the way it is? 

I'll get you a test on the 1.32 alpha ASAP

**Comment by jcklpe** [comment]
@thaider  Sadly not quite a fix. I get the following error with the new version:

```

Fatal error: Uncaught Error: Call to undefined function wfRunHooks() in /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php:581 Stack trace: #0 /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php(106): TweekiTemplate->checkVisibility('sidebar-left') #1 /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php(79): TweekiTemplate->renderPage(Object(TweekiTemplate)) #2 /var/www/mediawiki/includes/skins/SkinTemplate.php(227): TweekiTemplate->execute() #3 /var/www/mediawiki/includes/OutputPage.php(2597): SkinTemplate->outputPage() #4 /var/www/mediawiki/includes/exception/MWExceptionRenderer.php(136): OutputPage->output() #5 /var/www/mediawiki/includes/exception/MWExceptionRenderer.php(53): MWExceptionRenderer::reportHTML(Object(Error)) #6 /var/www/mediawiki/includes/exception/MWExceptionHandler.php(98): MWExceptionRenderer::output(Object(Error), 2) #7 /var/www/mediawiki/includes/exception/MWExceptionHandler.php(172): MWExceptionHandler::report(Object(Error)) #8 /var/www/mediawiki/includes/exception/MWExcepti in /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php on line 581
```

**Comment by thaider** [comment]
Oops, missed that one. Please try again...

I'm not a code wizard myself so I do have a basic understanding of how skinning in MW works but I can't really assess if it's an archaic way of doing it. It's possible, btw, that the forthcoming release of Tweeki (featuring Bootstrap 4) will include webpack support...

**Comment by jcklpe** [comment]
@thaider  Well it's a little bit closer to working! This time it's not a wfHooks error. Seems to be an issue with translate being called on "null"? 
```
    Notice: Undefined property: TweekiTemplate::$translator in /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php on line 305

    Fatal error: Uncaught Error: Call to a member function translate() on null in /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php:305 Stack trace: #0 /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php(827): TweekiTemplate->renderNavigation(Array) #1 /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php(684): TweekiTemplate->buildItems('TOOLBOX,PERSONA...', Array, 'navbar-right') #2 /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php(663): TweekiTemplate->renderNavbarElement('right') #3 /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php(139): TweekiTemplate->renderNavbar() #4 /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php(79): TweekiTemplate->renderPage(Object(TweekiTemplate)) #5 /var/www/mediawiki/includes/skins/SkinTemplate.php(227): TweekiTemplate->execute() #6 /var/www/mediawiki/includes/OutputPage.php(2597): SkinTemplate->outputPage() #7 /var/www/mediawiki/includes/exception/MWExceptionRenderer.php(136): OutputPage->output() #8 /var/www/mediawiki/includes/exception/ in /var/www/mediawiki/skins/Tweeki/includes/TweekiTemplate.php on line 305

```

I'm def no code wizard, but I think you probably outstrip me by a fair bit, haha. That adds to my confusion because I'm not sure if Mediwiki skins are built in an archaic and weird way, or if I'm just not a good enough coder yet. Hard for me to say!

Also webpack and bootstrap 4 support sound dope!

**Comment by thaider** [comment]
At least we're making progress ;) I made another update, please try if it happens to do the trick. I suppose, you havent't changed the content of ```MediaWiki:Tweeki-navbar-right```, right? 

If it still doesn't work, maybe you could try disabling all the other extensions and see if Tweeki is conflicting with one of them?

**Comment by jcklpe** [comment]
@thaider  Excellent! It's working! Woo! This thing does look good. I found an article that seems decently up to date and approachable on creating a sub skin for Vector. I'm going to take a crack at that this week, and if I can get the hang of it I may take a shot at making my own subskin for Tweeki too. If I can get the webpack or Bootstrap 4 stuff integrated before you do, I'll make a pull request, if that's of any help. This is by far the best skin I've seen for mediawiki. Very nice work!
