### ISSUE TITLE
[1.2.1] MediaWiki 1.35.1 Cannot Render Special Pages

### ISSUE THREAD

**Issue by aytimothy** [thaider/Tweeki#190]
I installed the latest (1.2.1) version of Tweeki (67846686fec148aeedfa3751bd9d0d47f1adedc1) on a brand new install of MediaWiki 1.35.1 and it fails to render any special page.  
Instead, I'm *sometimes* greeted with this error.

(It's populated because I literally wrote a backup script to grab every single page and then restore it as a bot user)

```
MediaWiki internal error.

Original exception: [af00399fa7889f05c819f2fb] /index.php?title=Special:UserLogin&returnto=Medarot+S+Wiki&useskin=tweeki TypeError from line 3974 of C:\Users\aytimothy\XAMPP\htdocs\includes\Title.php: Argument 1 passed to Title::equals() must implement interface MediaWiki\Linker\LinkTarget, null given, called in C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\Hooks.php on line 601
Backtrace:
#0 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\Hooks.php(601): Title->equals(NULL)
#1 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\Hooks.php(466): TweekiHooks::parseButtonLink(array, Parser, boolean)
#2 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(1127): TweekiHooks::parseButtons(string, Parser, boolean)
#3 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(1098): TweekiTemplate->renderCustomNavigation(array, array)
#4 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(888): TweekiTemplate->buildItems(string, array, string)
#5 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(818): TweekiTemplate->renderNavbarElement(string)
#6 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(154): TweekiTemplate->renderNavbar()
#7 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(85): TweekiTemplate->renderPage(TweekiTemplate)
#8 C:\Users\aytimothy\XAMPP\htdocs\includes\skins\SkinTemplate.php(129): TweekiTemplate->execute()
#9 C:\Users\aytimothy\XAMPP\htdocs\includes\skins\SkinTemplate.php(144): SkinTemplate->generateHTML()
#10 C:\Users\aytimothy\XAMPP\htdocs\includes\OutputPage.php(2615): SkinTemplate->outputPage()
#11 C:\Users\aytimothy\XAMPP\htdocs\includes\MediaWiki.php(947): OutputPage->output(boolean)
#12 C:\Users\aytimothy\XAMPP\htdocs\includes\MediaWiki.php(960): MediaWiki->{closure}()
#13 C:\Users\aytimothy\XAMPP\htdocs\includes\MediaWiki.php(543): MediaWiki->main()
#14 C:\Users\aytimothy\XAMPP\htdocs\index.php(53): MediaWiki->run()
#15 C:\Users\aytimothy\XAMPP\htdocs\index.php(46): wfIndexMain()
#16 {main}

Exception caught inside exception handler: [af00399fa7889f05c819f2fb] /index.php?title=Special:UserLogin&returnto=Medarot+S+Wiki&useskin=tweeki TypeError from line 3974 of C:\Users\aytimothy\XAMPP\htdocs\includes\Title.php: Argument 1 passed to Title::equals() must implement interface MediaWiki\Linker\LinkTarget, null given, called in C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\Hooks.php on line 601
Backtrace:
#0 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\Hooks.php(601): Title->equals(NULL)
#1 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\Hooks.php(466): TweekiHooks::parseButtonLink(array, Parser, boolean)
#2 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(1127): TweekiHooks::parseButtons(string, Parser, boolean)
#3 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(1098): TweekiTemplate->renderCustomNavigation(array, array)
#4 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(888): TweekiTemplate->buildItems(string, array, string)
#5 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(818): TweekiTemplate->renderNavbarElement(string)
#6 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(154): TweekiTemplate->renderNavbar()
#7 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\TweekiTemplate.php(85): TweekiTemplate->renderPage(TweekiTemplate)
#8 C:\Users\aytimothy\XAMPP\htdocs\includes\skins\SkinTemplate.php(129): TweekiTemplate->execute()
#9 C:\Users\aytimothy\XAMPP\htdocs\includes\skins\SkinTemplate.php(144): SkinTemplate->generateHTML()
#10 C:\Users\aytimothy\XAMPP\htdocs\includes\OutputPage.php(2615): SkinTemplate->outputPage()
#11 C:\Users\aytimothy\XAMPP\htdocs\includes\exception\MWExceptionRenderer.php(153): OutputPage->output()
#12 C:\Users\aytimothy\XAMPP\htdocs\includes\exception\MWExceptionRenderer.php(65): MWExceptionRenderer::reportHTML(TypeError)
#13 C:\Users\aytimothy\XAMPP\htdocs\includes\exception\MWExceptionHandler.php(106): MWExceptionRenderer::output(TypeError, integer)
#14 C:\Users\aytimothy\XAMPP\htdocs\includes\exception\MWExceptionHandler.php(185): MWExceptionHandler::report(TypeError)
#15 C:\Users\aytimothy\XAMPP\htdocs\includes\MediaWiki.php(579): MWExceptionHandler::handleException(TypeError, string)
```

All named pages seem to work fine though.

[![https://i.imgur.com/1mG8Und.png](https://i.imgur.com/1mG8Und.png)](https://i.imgur.com/1mG8Und.png)

(Regular namespace page)

[![https://i.imgur.com/KtQsskO.png](https://i.imgur.com/KtQsskO.png)](https://i.imgur.com/KtQsskO.png)

(File namespace page)

But not for system pages.

[![https://i.imgur.com/74fZeo5.png](https://i.imgur.com/74fZeo5.png)](https://i.imgur.com/74fZeo5.png)

(Wiki, in my case `Medarot_S_Wiki` and Special namespace pages)

It is pot luck whether the error message even appears at all even with `$wgShowExceptionDetails = true`.

The website is live if you want to [try](https://medarots.projectrisingbeetle.com/index.php?title=Special:UserLogin&returnto=Medarot+S+Wiki&useskin=tweeki) [it](http://medarots.projectrisingbeetle.com/wiki/Medarot_S_Wiki:About?useskin=tweeki) yourself.

----

Oh yeah, I managed to recreate #185 too. All you need to do just open any page and check the [JavaScript console](https://i.imgur.com/9eOYZtJ.png).

```
load.php?lang=en&modules=startup&only=scripts&raw=1&skin=vector:51 [9c1e9d62776a808e1995c47c] /load.php?lang=en&modules=startup&only=scripts&raw=1&skin=vector   
BadMethodCallException from line 851 of C:\Users\aytimothy\XAMPP\htdocs\includes\session\SessionManager.php: Sessions are disabled for this entry point
Backtrace:
#0 C:\Users\aytimothy\XAMPP\htdocs\includes\session\SessionManager.php(220): MediaWiki\Session\SessionManager->getSessionFromInfo(MediaWiki\Session\SessionInfo, WebRequest)
#1 C:\Users\aytimothy\XAMPP\htdocs\includes\WebRequest.php(826): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#2 C:\Users\aytimothy\XAMPP\htdocs\includes\user\User.php(1221): WebRequest->getSession()
#3 C:\Users\aytimothy\XAMPP\htdocs\includes\user\User.php(388): User->loadFromSession()
#4 C:\Users\aytimothy\XAMPP\htdocs\includes\user\User.php(2125): User->load()
#5 C:\Users\aytimothy\XAMPP\htdocs\includes\user\User.php(3064): User->getId()
#6 C:\Users\aytimothy\XAMPP\htdocs\includes\user\UserOptionsManager.php(584): User->isRegistered()
#7 C:\Users\aytimothy\XAMPP\htdocs\includes\user\UserOptionsManager.php(487): MediaWiki\User\UserOptionsManager->getCacheKey(User)
#8 C:\Users\aytimothy\XAMPP\htdocs\includes\user\UserOptionsManager.php(135): MediaWiki\User\UserOptionsManager->loadUserOptions(User, integer)
#9 C:\Users\aytimothy\XAMPP\htdocs\includes\user\User.php(2665): MediaWiki\User\UserOptionsManager->getOption(User, string, NULL, boolean)
#10 C:\Users\aytimothy\XAMPP\htdocs\includes\context\RequestContext.php(416): User->getOption(string)
#11 C:\Users\aytimothy\XAMPP\htdocs\includes\context\ContextSource.php(150): RequestContext->getSkin()
#12 C:\Users\aytimothy\XAMPP\htdocs\skins\Tweeki\includes\Hooks.php(52): ContextSource->getSkin()
#13 C:\Users\aytimothy\XAMPP\htdocs\includes\HookContainer\HookContainer.php(320): TweekiHooks::onParserFirstCallInit(Parser)
#14 C:\Users\aytimothy\XAMPP\htdocs\includes\HookContainer\HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#15 C:\Users\aytimothy\XAMPP\htdocs\includes\HookContainer\HookRunner.php(2959): MediaWiki\HookContainer\HookContainer->run(string, array)
#16 C:\Users\aytimothy\XAMPP\htdocs\includes\parser\Parser.php(532): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
#17 C:\Users\aytimothy\XAMPP\htdocs\includes\parser\Parser.php(477): Parser->firstCallInit()
#18 C:\Users\aytimothy\XAMPP\htdocs\includes\parser\ParserFactory.php(142): Parser->__construct(MediaWiki\Config\ServiceOptions, MagicWordFactory, LanguageEn, ParserFactory, string, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer)
#19 C:\Users\aytimothy\XAMPP\htdocs\includes\ServiceWiring.php(818): ParserFactory->create()
#20 C:\Users\aytimothy\XAMPP\htdocs\vendor\wikimedia\services\src\ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
#21 C:\Users\aytimothy\XAMPP\htdocs\vendor\wikimedia\services\src\ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#22 C:\Users\aytimothy\XAMPP\htdocs\includes\MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService(string)
#23 C:\Users\aytimothy\XAMPP\htdocs\includes\cache\MessageCache.php(1249): MediaWiki\MediaWikiServices->getParser()
#24 C:\Users\aytimothy\XAMPP\htdocs\includes\cache\MessageCache.php(1228): MessageCache->getParser()
#25 C:\Users\aytimothy\XAMPP\htdocs\includes\language\Message.php(1287): MessageCache->transform(string, boolean, LanguageEn, NULL)
#26 C:\Users\aytimothy\XAMPP\htdocs\includes\language\Message.php(894): Message->transformText(string)
#27 C:\Users\aytimothy\XAMPP\htdocs\includes\language\Message.php(954): Message->toString(string)
#28 C:\Users\aytimothy\XAMPP\htdocs\includes\EditPage.php(3836): Message->text()
#29 C:\Users\aytimothy\XAMPP\htdocs\extensions\VisualEditor\includes\VisualEditorDataModule.php(70): EditPage::getCopyrightWarning(Title, string, string)
#30 C:\Users\aytimothy\XAMPP\htdocs\extensions\VisualEditor\includes\VisualEditorDataModule.php(25): VisualEditorDataModule->getMessageInfo(ResourceLoaderContext)
#31 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoaderModule.php(736): VisualEditorDataModule->getScript(ResourceLoaderContext)
#32 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#33 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoaderModule.php(839): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#34 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoaderStartUpModule.php(209): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#35 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoaderStartUpModule.php(405): ResourceLoaderStartUpModule->getModuleRegistrations(ResourceLoaderContext)
#36 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoaderModule.php(736): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#37 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#38 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoaderModule.php(839): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#39 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoader.php(775): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#40 [internal function]: ResourceLoader->{closure}(string)
#41 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoader.php(787): array_map(Closure, array)
#42 C:\Users\aytimothy\XAMPP\htdocs\includes\resourceloader\ResourceLoader.php(874): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#43 C:\Users\aytimothy\XAMPP\htdocs\load.php(51): ResourceLoader->respond(ResourceLoaderContext)
#44 C:\Users\aytimothy\XAMPP\htdocs\load.php(38): wfLoadMain()
#45 {main}
```

This occurs both on the live server and on an internal instance I spun up (the only thing they share is the same secret key and database), both created from scratch.

**Comment by aytimothy** [comment]
Appears to be a dupe of #186
