### ISSUE TITLE
Mediawiki 1.35 Special:RecentChanges - stuck progress indicator (has workaround)

### ISSUE THREAD

**Issue by sergem155** [thaider/Tweeki#193]
With Tweeki skin enabled, navigating to Special:RecentChanges shows the list of changes, but the active filters section displays progress dots forever. The console shows an error:

```load.php?lang=en&modules=jquery%2Coojs-ui-core%2Coojs-ui-widgets|mediawiki.rcfilters.filters.ui&skin=tweeki&version=11qii:44 [7b4fa057c355125309bac2b6] /load.php?lang=en&modules=jquery%2Coojs-ui-core%2Coojs-ui-widgets%7Cmediawiki.rcfilters.filters.ui&skin=tweeki&version=11qii   BadMethodCallException from line 848 of /helpsite/includes/session/SessionManager.php: Sessions are disabled for this entry point
Backtrace:
#0 /helpsite/includes/session/SessionManager.php(220): MediaWiki\Session\SessionManager->getSessionFromInfo(MediaWiki\Session\SessionInfo, WebRequest)
#1 /helpsite/includes/WebRequest.php(826): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#2 /helpsite/includes/user/User.php(1221): WebRequest->getSession()
#3 /helpsite/includes/user/User.php(388): User->loadFromSession()
#4 /helpsite/includes/user/User.php(2130): User->load()
#5 /helpsite/includes/user/User.php(3069): User->getId()
#6 /helpsite/includes/user/UserOptionsManager.php(584): User->isRegistered()
#7 /helpsite/includes/user/UserOptionsManager.php(487): MediaWiki\User\UserOptionsManager->getCacheKey(User)
#8 /helpsite/includes/user/UserOptionsManager.php(135): MediaWiki\User\UserOptionsManager->loadUserOptions(User, integer)
#9 /helpsite/includes/user/User.php(2670): MediaWiki\User\UserOptionsManager->getOption(User, string, NULL, boolean)
#10 /helpsite/includes/context/RequestContext.php(416): User->getOption(string)
#11 /helpsite/includes/context/ContextSource.php(150): RequestContext->getSkin()
#12 /helpsite/skins/Tweeki/includes/Hooks.php(52): ContextSource->getSkin()
#13 /helpsite/includes/HookContainer/HookContainer.php(321): TweekiHooks::onParserFirstCallInit(Parser)
#14 /helpsite/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#15 /helpsite/includes/HookContainer/HookRunner.php(2960): MediaWiki\HookContainer\HookContainer->run(string, array)
#16 /helpsite/includes/parser/Parser.php(532): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
#17 /helpsite/includes/parser/Parser.php(477): Parser->firstCallInit()
#18 /helpsite/includes/parser/ParserFactory.php(142): Parser->__construct(MediaWiki\Config\ServiceOptions, MagicWordFactory, LanguageEn, ParserFactory, string, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer)
#19 /helpsite/includes/ServiceWiring.php(817): ParserFactory->create()
#20 /helpsite/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
#21 /helpsite/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#22 /helpsite/includes/MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService(string)
#23 /helpsite/includes/cache/MessageCache.php(1249): MediaWiki\MediaWikiServices->getParser()
#24 /helpsite/includes/cache/MessageCache.php(1276): MessageCache->getParser()
#25 /helpsite/includes/language/Message.php(1258): MessageCache->parse(string, Title, boolean, boolean, LanguageEn)
#26 /helpsite/includes/language/Message.php(889): Message->parseText(string)
#27 /helpsite/includes/language/Message.php(942): Message->toString(string)
#28 /helpsite/includes/specialpage/ChangesListSpecialPage.php(976): Message->parse()
#29 /helpsite/includes/specialpage/ChangesListSpecialPage.php(887): ChangesListSpecialPage::getChangeTagList(ResourceLoaderContext)
#30 /helpsite/includes/resourceloader/ResourceLoaderFileModule.php(1308): ChangesListSpecialPage::getRcFiltersConfigVars(ResourceLoaderContext, GlobalVarConfig, NULL)
#31 /helpsite/includes/resourceloader/ResourceLoaderFileModule.php(347): ResourceLoaderFileModule->getPackageFiles(ResourceLoaderContext)
#32 /helpsite/includes/resourceloader/ResourceLoaderModule.php(736): ResourceLoaderFileModule->getScript(ResourceLoaderContext)
#33 /helpsite/includes/resourceloader/ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#34 /helpsite/includes/resourceloader/ResourceLoader.php(1191): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#35 /helpsite/includes/resourceloader/ResourceLoader.php(899): ResourceLoader->makeModuleResponse(ResourceLoaderContext, array, array)
#36 /helpsite/load.php(51): ResourceLoader->respond(ResourceLoaderContext)
#37 /helpsite/load.php(38): wfLoadMain()
#38 {main} 
```
I commented out the conditional in Hooks.php:
		if( $GLOBALS['wgOut']->getSkin()->getSkinName() == 'tweeki' ) {

and the issue has gone away, but I guess this is just a mitigation, not a solution.

**Comment by thaider** [comment]
should be solved by palladox's pull request #200

**Comment by Fredrilj** [comment]
After updating Tweeki, including palladox pull request #200, I can confirm that Special:RecentChanges now shows the list, but even with $wgAllowSiteCSSOnRestrictedPages = true; there is some offset issues. Eg. icons laying over text and box with list of abbreviations has problems to adjust to different screen sizes.

**Comment by thaider** [comment]
Thanks for reporting, I opened a new issue (#206) for that.
