### ISSUE TITLE
Issue when calling in /../w/skins/Tweeki/includes/Hooks.php on line 601

### ISSUE THREAD

**Issue by kghbln** [thaider/Tweeki#208]
## Setup
Software | Version
-- | --
MediaWiki | 1.35.2 (e1f115d)17:40, 17. Mai 2021
PHP | 7.4.3 (apache2handler)
MariaDB | 10.3.29-MariaDB-0ubuntu0.20.04.1
ICU | 66.1

Bezeichnung | Version | Lizenz | Beschreibung | Autoren
-- | -- | -- | -- | --
Tweeki | 1.2.1 (6784668) 20:20, 3. Jan. 2021 | GPL-2.0-or-later | A skin based on Bootstrap | Tobias Haider

## Issue
```
2021-06-10 08:43:43 98703-kalmia mediawiki_db: [c0d8749bdaf419cb0c71753f] /w/index.php?title=Speciaal:Aanmelden&returnto=Hoofdpagina   TypeError from line 3974 of /../w/includes/Title.php: Argument 1 passed to Title::equals() must implement interface MediaWiki\Linker\LinkTarget, null given, called in /../w/skins/Tweeki/includes/Hooks.php on line 601
```
The server gives an error 500 on this. This happens when enabling a caching provider with `$wgMainCacheType` which is what probably everybody wants to do. Thus is really a big issue.

## Backtrace
```
#0 /../w/skins/Tweeki/includes/Hooks.php(601): Title->equals()
#1 /../w/skins/Tweeki/includes/Hooks.php(466): TweekiHooks::parseButtonLink()
#2 /../w/skins/Tweeki/includes/TweekiTemplate.php(1127): TweekiHooks::parseButtons()
#3 /../w/skins/Tweeki/includes/TweekiTemplate.php(1098): TweekiTemplate->renderCustomNavigation()
#4 /../w/skins/Tweeki/includes/TweekiTemplate.php(888): TweekiTemplate->buildItems()
#5 /../w/skins/Tweeki/includes/TweekiTemplate.php(818): TweekiTemplate->renderNavbarElement()
#6 /../w/skins/Tweeki/includes/TweekiTemplate.php(154): TweekiTemplate->renderNavbar()
#7 /../w/skins/Tweeki/includes/TweekiTemplate.php(85): TweekiTemplate->renderPage()
#8 /../w/includes/skins/SkinTemplate.php(129): TweekiTemplate->execute()
#9 /../w/includes/skins/SkinTemplate.php(144): SkinTemplate->generateHTML()
#10 /../w/includes/OutputPage.php(2622): SkinTemplate->outputPage()
#11 /../w/includes/MediaWiki.php(947): OutputPage->output()
#12 /../w/includes/MediaWiki.php(960): MediaWiki->{closure}()
#13 /../w/includes/MediaWiki.php(543): MediaWiki->main()
#14 /../w/index.php(53): MediaWiki->run()
#15 /../w/index.php(46): wfIndexMain()
#16 {main}
```

**Comment by kghbln** [comment]
@thaider This issue appears to be resolved on the recent version v1.2.2 which I for some reason missed completely. Thanks a bunch for your work! I am so happy so see this big pain the the you know where go away. :)
